"""introduce rbac

Revision ID: 243af2031c5e
Revises: 4ae177e3d610
Create Date: 2025-10-20 18:26:53.714508

"""
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PGUUID


# revision identifiers, used by Alembic.
revision: str = '243af2031c5e'
down_revision: Union[str, Sequence[str], None] = '4ae177e3d610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    conn = op.get_bind()
    
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.add_column('users', sa.Column('auth_version', sa.Integer(), server_default='1', nullable=False))
    
    roles_table = sa.table(
        "roles",
        sa.column("id", sa.Uuid()),
        sa.column("slug", sa.String()),
        sa.column("name", sa.String()),
        sa.column("description", sa.Text()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    
    member_role_id = uuid4()
    admin_role_id = uuid4()
    merchant_role_id = uuid4()
    
    op.bulk_insert(
        roles_table,
        [
            {
                "id": member_role_id,
                "slug": "member",
                "name": "Member",
                "description": "Default role for registered users",
            },
            {
                "id": admin_role_id,
                "slug": "admin",
                "name": "Administrator",
                "description": "Full administrative access",
            },
            {
                "id": merchant_role_id,
                "slug": "merchant",
                "name": "Merchant",
                "description": "Merchant role for users who have organization",
            },
        ],
    )
    
    stmt_member = (
        sa.text(
            "INSERT INTO user_roles (user_id, role_id) "
            "SELECT id, :member_role_id FROM users"
        )
        .bindparams(
            sa.bindparam(
                "member_role_id", member_role_id, type_=PGUUID(as_uuid=True)
            )
        )
    )
    conn.execute(stmt_member)
    
    stmt_admin = (
        sa.text(
            "INSERT INTO user_roles (user_id, role_id) "
            "SELECT id, :admin_role_id FROM users WHERE is_admin = TRUE"
        )
        .bindparams(
            sa.bindparam(
                "admin_role_id", admin_role_id, type_=PGUUID(as_uuid=True)
            )
        )
    )
    conn.execute(stmt_admin)

    stmt_merchant = (
        sa.text(
            "INSERT INTO user_roles (user_id, role_id) "
            "SELECT DISTINCT owner_user_id, :merchant_role_id FROM organizations "
            "WHERE owner_user_id IS NOT NULL"
        )
        .bindparams(
            sa.bindparam(
                "merchant_role_id", merchant_role_id, type_=PGUUID(as_uuid=True)
            )
        )
    )
    conn.execute(stmt_merchant)

    op.execute(
        sa.text(
            "INSERT INTO org_memberships (org_id, user_id, role, created_at, accepted_at) "
            "SELECT id, owner_user_id, 'OWNER'::membership_role, now(), now() FROM organizations "
            "WHERE owner_user_id IS NOT NULL "
            "ON CONFLICT (org_id, user_id) DO UPDATE SET role = EXCLUDED.role"
        )
    )

    op.drop_column('users', 'is_admin')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    
    op.execute(
        sa.text(
            "UPDATE users SET is_admin = TRUE "
            "WHERE id IN ("
            "    SELECT user_id FROM user_roles ur "
            "    JOIN roles r ON r.id = ur.role_id "
            "    WHERE r.slug = 'admin'"
            ")"
        )
    )
    
    op.drop_column('users', 'auth_version')
        
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
