"""add status to cart_items

Revision ID: 255bfef7f65f
Revises: 4ad51efb1255
Create Date: 2025-08-29 23:26:14.848096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '255bfef7f65f'
down_revision: Union[str, Sequence[str], None] = '4ad51efb1255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    cart_item_status_enum = postgresql.ENUM('ACTIVE', 'LOCKED', 'PURCHASED', 'REMOVED', name='cartitemstatus')
    cart_item_status_enum.create(op.get_bind())
    
    op.add_column('cart_items', sa.Column('order_id', sa.Uuid(), nullable=True, comment='Order ID'))
    op.add_column('cart_items', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True, comment='Date and time when the item was locked'))
    op.add_column('cart_items', sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True, comment='Date and time when the lock expires'))
    op.create_foreign_key('cart_item_order_id_fkey', 'cart_items', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    
    op.add_column('cart_items', sa.Column('status', postgresql.ENUM(name='cartitemstatus'), nullable=True, comment='Cart item status'))
    op.execute("UPDATE cart_items SET status = 'ACTIVE'")
    op.alter_column('cart_items', 'status', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_item_order_id_fkey', 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'lock_expires_at')
    op.drop_column('cart_items', 'locked_at')
    op.drop_column('cart_items', 'status')
    op.drop_column('cart_items', 'order_id')
    
    enum = postgresql.ENUM(name='cartitemstatus', create_type=False)
    enum.drop(op.get_bind())
    # ### end Alembic commands ###
