"""create products

Revision ID: 362339d94668
Revises: ddd36475f4df
Create Date: 2025-08-20 20:45:24.987233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '362339d94668'
down_revision: Union[str, Sequence[str], None] = 'ddd36475f4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False, comment='Seller organization ID'),
    sa.Column('brand', sa.String(), nullable=False, comment='Part brand/manufacturer'),
    sa.Column('part_number', sa.String(), nullable=False, comment='Part number (OEM or aftermarket)'),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Price in USD'),
    sa.Column('condition', postgresql.ENUM('NEW', 'USED', name='product_condition'), nullable=False, comment='Part condition'),
    sa.Column('description', sa.Text(), nullable=True, comment='Product listing description'),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='product_status'), nullable=False, comment='Publication status'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False, comment='Product ID'),
    sa.Column('url', sa.String(), nullable=False, comment='Media file URL'),
    sa.Column('alt', sa.String(), nullable=True, comment='Alternative text'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_media')
    op.drop_table('products')
    # ### end Alembic commands ###
