"""update stripe related tables

Revision ID: 37a87fe40e24
Revises: 210ba263ad56
Create Date: 2025-08-20 11:21:20.003692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37a87fe40e24'
down_revision: Union[str, Sequence[str], None] = '210ba263ad56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('organizations', sa.Column('stripe_charges_enabled', sa.Boolean(), nullable=False))
    op.add_column('organizations', sa.Column('stripe_payouts_enabled', sa.Boolean(), nullable=False))
    op.add_column('organizations', sa.Column('stripe_disabled_reason', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('stripe_business_type', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('stripe_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('organizations', sa.Column('stripe_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('organizations', sa.Column('stripe_details_submitted', sa.Boolean(), nullable=False))
    op.add_column('organizations', sa.Column('stripe_onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('last_stripe_sync_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('organizations', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('organizations', 'last_stripe_sync_at')
    op.drop_column('organizations', 'stripe_onboarding_completed_at')
    op.drop_column('organizations', 'stripe_details_submitted')
    op.drop_column('organizations', 'stripe_requirements')
    op.drop_column('organizations', 'stripe_capabilities')
    op.drop_column('organizations', 'stripe_business_type')
    op.drop_column('organizations', 'stripe_disabled_reason')
    op.drop_column('organizations', 'stripe_payouts_enabled')
    op.drop_column('organizations', 'stripe_charges_enabled')
    op.drop_table('stripe_events')
    # ### end Alembic commands ###
