"""update products table

Revision ID: 381383b905b0
Revises: 172ee62192a0
Create Date: 2025-08-25 20:45:41.643331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '381383b905b0'
down_revision: Union[str, Sequence[str], None] = '172ee62192a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    stock_type_enum = postgresql.ENUM('UNIQUE', 'STOCK', name='product_stock_type')
    originality_enum = postgresql.ENUM('OEM', 'AFTERMARKET', name='product_originality')
    stock_type_enum.create(op.get_bind())
    originality_enum.create(op.get_bind())
    
    op.add_column('products', sa.Column('make_id', sa.Integer(), nullable=True, comment='Make ID (vPIC)'))
    op.add_column('products', sa.Column('title', sa.String(), nullable=True, comment='Product title'))
    op.add_column('products', sa.Column('stock_type', postgresql.ENUM('UNIQUE', 'STOCK', name='product_stock_type'), nullable=True, comment='Part stock type'))
    op.add_column('products', sa.Column('quantity_original', sa.Integer(), nullable=True, comment='Original part stock quantity'))
    op.add_column('products', sa.Column('quantity_on_hand', sa.Integer(), nullable=True, comment='Part stock quantity on hand'))
    op.add_column('products', sa.Column('originality', postgresql.ENUM('OEM', 'AFTERMARKET', name='product_originality'), nullable=True, comment='Part originality'))
    op.add_column('products', sa.Column('allow_cart', sa.Boolean(), nullable=True, comment='Allow adding to cart'))
    op.add_column('products', sa.Column('allow_chat', sa.Boolean(), nullable=True, comment='Allow chat with seller'))
    
    op.execute("""
        UPDATE products SET 
            make_id = 449,
            title = 'Auto Part',
            stock_type = 'STOCK',
            quantity_original = 2,
            quantity_on_hand = 2,
            originality = 'OEM',
            allow_cart = true,
            allow_chat = true
        WHERE make_id IS NULL
    """)
    
    op.alter_column('products', 'make_id', nullable=False)
    op.alter_column('products', 'title', nullable=False)
    op.alter_column('products', 'stock_type', nullable=False)
    op.alter_column('products', 'quantity_original', nullable=False)
    op.alter_column('products', 'quantity_on_hand', nullable=False)
    op.alter_column('products', 'originality', nullable=False)
    op.alter_column('products', 'allow_cart', nullable=False)
    op.alter_column('products', 'allow_chat', nullable=False)
    
    op.create_index('ix_products_org_status', 'products', ['org_id', 'status'], unique=False)
    op.create_index(op.f('ix_products_part_number'), 'products', ['part_number'], unique=False)
    op.create_foreign_key('fk_products_makes', 'products', 'makes', ['make_id'], ['make_id'])
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Part brand/manufacturer'))
    op.drop_constraint('fk_products_makes', 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_part_number'), table_name='products')
    op.drop_index('ix_products_org_status', table_name='products')
    op.drop_column('products', 'allow_chat')
    op.drop_column('products', 'allow_cart')
    op.drop_column('products', 'originality')
    op.drop_column('products', 'quantity_on_hand')
    op.drop_column('products', 'quantity_original')
    op.drop_column('products', 'stock_type')
    op.drop_column('products', 'title')
    op.drop_column('products', 'make_id')
    
    stock_type_enum = postgresql.ENUM('UNIQUE', 'STOCK', name='product_stock_type')
    originality_enum = postgresql.ENUM('OEM', 'AFTERMARKET', name='product_originality')
    
    stock_type_enum.drop(op.get_bind())
    originality_enum.drop(op.get_bind())
    # ### end Alembic commands ###
