"""add stripe checkout session field to orders table

Revision ID: 4ad51efb1255
Revises: 3e28e3d5858e
Create Date: 2025-08-28 22:43:22.260161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad51efb1255'
down_revision: Union[str, Sequence[str], None] = '3e28e3d5858e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stripe_checkout_session_id', sa.String(), nullable=True, comment='Stripe Checkout Session ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'stripe_checkout_session_id')
    # ### end Alembic commands ###
