"""create reviews and ratings related tables

Revision ID: 4ae177e3d610
Revises: ef6f58f353eb
Create Date: 2025-10-14 18:19:04.850102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae177e3d610'
down_revision: Union[str, Sequence[str], None] = 'ef6f58f353eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False, comment='User ID'),
    sa.Column('product_id', sa.Uuid(), nullable=False, comment='Product ID'),
    sa.Column('seller_org_id', sa.Uuid(), nullable=False, comment='Product ID'),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=False, comment='User ID'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Rating'),
    sa.Column('title', sa.Text(), nullable=True, comment='Review title'),
    sa.Column('body', sa.Text(), nullable=True, comment='Review body'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='rating_limit_product_reviews'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reviewer_user_id', 'product_id', name='unique_user_product_rating')
    )
    op.create_table('seller_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False, comment='User ID'),
    sa.Column('seller_org_id', sa.Uuid(), nullable=False, comment='Product ID'),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=False, comment='User ID'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Rating'),
    sa.Column('title', sa.Text(), nullable=True, comment='Review title'),
    sa.Column('body', sa.Text(), nullable=True, comment='Review body'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='rating_limit_seller_reviews'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reviewer_user_id', 'order_item_id', name='unique_user_seller_rating')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller_reviews')
    op.drop_table('product_reviews')
    # ### end Alembic commands ###
