"""create organization related tables

Revision ID: 779a3160529b
Revises: fa110bc90883
Create Date: 2025-08-19 17:26:12.755102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '779a3160529b'
down_revision: Union[str, Sequence[str], None] = 'fa110bc90883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', postgresql.ENUM('SUPPLIER', 'WORKSHOP', name='organization_type'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_account_id', sa.String(), nullable=True),
    sa.Column('kyc_status', postgresql.ENUM('NOT_STARTED', 'PENDING', 'VERIFIED', 'REJECTED', name='kyc_status'), nullable=False),
    sa.Column('payout_schedule', postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', name='payout_schedule'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('organizations_name_trgm', 'organizations', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('org_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'ADMIN', 'STAFF', 'ACCOUNTANT', name='membership_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'email', name='uq_org_invite_org_email'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('token', name='uq_org_invite_token')
    )
    op.create_table('org_memberships',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'ADMIN', 'STAFF', 'ACCOUNTANT', name='membership_role'), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('org_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_memberships')
    op.drop_table('org_invites')
    op.drop_index('organizations_name_trgm', table_name='organizations', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('organizations')
    # ### end Alembic commands ###
