"""add trgm indeces for faster search

Revision ID: 783460c10d11
Revises: 381383b905b0
Create Date: 2025-08-25 23:11:59.522883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783460c10d11'
down_revision: Union[str, Sequence[str], None] = '381383b905b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_makes_name_trgm', 'makes', ['make_name'], unique=False, postgresql_using='gin', postgresql_ops={'make_name': 'gin_trgm_ops'})
    op.create_index('ix_products_description_trgm', 'products', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index('ix_products_part_number_trgm', 'products', ['part_number'], unique=False, postgresql_using='gin', postgresql_ops={'part_number': 'gin_trgm_ops'})
    op.create_index('ix_products_title_trgm', 'products', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_title_trgm', table_name='products', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_products_part_number_trgm', table_name='products', postgresql_using='gin', postgresql_ops={'part_number': 'gin_trgm_ops'})
    op.drop_index('ix_products_description_trgm', table_name='products', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_index('ix_makes_name_trgm', table_name='makes', postgresql_using='gin', postgresql_ops={'make_name': 'gin_trgm_ops'})
    # ### end Alembic commands ###
