"""add garage_vehicles table

Revision ID: 8fb9bd5fda97
Revises: 08555972e533
Create Date: 2025-08-22 14:54:32.080906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fb9bd5fda97'
down_revision: Union[str, Sequence[str], None] = '08555972e533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garage_vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('vin_decoded', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['makes.make_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id', 'year'], ['model_years.model_id', 'model_years.year'], name='fk_garage_model_year', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.vehicle_type_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('garage_vehicles')
    # ### end Alembic commands ###
