"""update products and carts

Revision ID: a45fac235379
Revises: 783460c10d11
Create Date: 2025-08-26 17:31:13.341204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45fac235379'
down_revision: Union[str, Sequence[str], None] = '783460c10d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('title', sa.String(), nullable=False, comment='Product title snapshot'))
    op.add_column('cart_items', sa.Column('description', sa.String(), nullable=True, comment='Product description snapshot'))
    op.add_column('cart_items', sa.Column('part_number', sa.String(), nullable=False, comment='Product part number snapshot'))
    op.alter_column('cart_items', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_comment='Price per unit when added to cart (USD)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_items', 'unit_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Price per unit when added to cart (USD)',
               existing_nullable=False)
    op.drop_column('cart_items', 'part_number')
    op.drop_column('cart_items', 'description')
    op.drop_column('cart_items', 'title')
    # ### end Alembic commands ###
