"""create orders related tables

Revision ID: a617fb5ddf4a
Revises: a45fac235379
Create Date: 2025-08-28 21:24:57.861964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a617fb5ddf4a'
down_revision: Union[str, Sequence[str], None] = 'a45fac235379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=False, comment='Buyer user ID'),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True, comment='Stripe Payment Intent ID'),
    sa.Column('payment_status', postgresql.ENUM('PENDING', 'PAID', 'REFUNDED', 'FAILED', 'CANCELLED', 'EXPIRED', name='paymentstatus'), nullable=False, comment='Order payment status'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total order amount in USD'),
    sa.Column('total_items', sa.Integer(), nullable=False, comment='Total number of items in order'),
    sa.Column('unique_items', sa.Integer(), nullable=False, comment='Total number of unique items in order'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Order notes from buyer'),
    sa.Column('shipping_address', sa.Text(), nullable=True, comment='Shipping address JSON'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False, comment='Order ID'),
    sa.Column('product_id', sa.Uuid(), nullable=True, comment='Product ID'),
    sa.Column('seller_org_id', sa.Uuid(), nullable=False, comment='Seller organization ID'),
    sa.Column('cart_item_id', sa.Uuid(), nullable=True, comment='Cart item ID'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Quantity ordered'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Price per unit at time of purchase (USD)'),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total price for this item (quantity * unit_price)'),
    sa.Column('product_make_id', sa.Integer(), nullable=False, comment='Product make ID at time of purchase'),
    sa.Column('product_make_name', sa.String(), nullable=False, comment='Product make name at time of purchase'),
    sa.Column('product_part_number', sa.String(), nullable=False, comment='Product part number at time of purchase'),
    sa.Column('product_condition', postgresql.ENUM('NEW', 'USED', name='productcondition'), nullable=False, comment='Product condition at time of purchase'),
    sa.Column('product_title', sa.String(), nullable=False, comment='Product title at time of purchase'),
    sa.Column('product_description', sa.Text(), nullable=True, comment='Product description at time of purchase'),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus'), nullable=False, comment='Order status'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_item_id'], ['cart_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_make_id'], ['makes.make_id'], ),
    sa.ForeignKeyConstraint(['seller_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
