"""create auto related tables

Revision ID: aef1e0dddb2b
Revises: 362339d94668
Create Date: 2025-08-21 17:05:20.127188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef1e0dddb2b'
down_revision: Union[str, Sequence[str], None] = '362339d94668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makes',
    sa.Column('make_id', sa.Integer(), nullable=False, comment='vPIC make ID'),
    sa.Column('make_name', sa.String(), nullable=False, comment='Official make name'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('make_id')
    )
    op.create_table('manufacturers',
    sa.Column('manufacturer_id', sa.Integer(), nullable=False, comment='vPIC manufacturer ID'),
    sa.Column('name', sa.String(), nullable=False, comment='Official manufacturer name'),
    sa.Column('mfr_common_name', sa.String(), nullable=True, comment='Common name or brand name'),
    sa.Column('country', sa.String(), nullable=True, comment='Country of manufacturer'),
    sa.Column('status', sa.String(), nullable=True, comment='Manufacturer status'),
    sa.Column('type', sa.String(), nullable=True, comment='Manufacturer type or vehicle types'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('manufacturer_id')
    )
    op.create_table('vehicle_types',
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('manufacturer_make',
    sa.Column('manufacturer_id', sa.Integer(), nullable=False, comment='vPIC manufacturer ID'),
    sa.Column('make_id', sa.Integer(), nullable=False, comment='vPIC make ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['makes.make_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.manufacturer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manufacturer_id', 'make_id')
    )
    op.create_table('models',
    sa.Column('model_id', sa.Integer(), autoincrement=True, nullable=False, comment='Surrogate primary key for model'),
    sa.Column('make_id', sa.Integer(), nullable=False, comment='Reference to the make this model belongs to'),
    sa.Column('model_name', sa.String(), nullable=False, comment='Name of the vehicle model'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['makes.make_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('model_years',
    sa.Column('model_id', sa.Integer(), nullable=False, comment='Reference to the model'),
    sa.Column('year', sa.Integer(), nullable=False, comment='Production year for the model'),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True, comment='Optional reference to vehicle type for this model year'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.vehicle_type_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_id', 'year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_years')
    op.drop_table('models')
    op.drop_table('manufacturer_make')
    op.drop_table('vehicle_types')
    op.drop_table('manufacturers')
    op.drop_table('makes')
    # ### end Alembic commands ###
