"""remove unused data

Revision ID: ddd36475f4df
Revises: 37a87fe40e24
Create Date: 2025-08-20 15:53:48.587098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddd36475f4df'
down_revision: Union[str, Sequence[str], None] = '37a87fe40e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'stripe_payouts_enabled')
    op.drop_column('organizations', 'stripe_details_submitted')
    op.drop_column('organizations', 'stripe_business_type')
    op.drop_column('organizations', 'stripe_charges_enabled')
    op.drop_column('organizations', 'stripe_disabled_reason')
    op.drop_column('organizations', 'last_stripe_sync_at')
    op.drop_column('organizations', 'stripe_requirements')
    op.drop_column('organizations', 'stripe_onboarding_completed_at')
    op.drop_column('organizations', 'stripe_capabilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('stripe_capabilities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('stripe_onboarding_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('stripe_requirements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('last_stripe_sync_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('stripe_disabled_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('stripe_charges_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('stripe_business_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('stripe_details_submitted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('stripe_payouts_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
