"""update orders table

Revision ID: ef6f58f353eb
Revises: 255bfef7f65f
Create Date: 2025-09-20 23:07:16.132517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6f58f353eb'
down_revision: Union[str, Sequence[str], None] = '255bfef7f65f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('carrier_code', sa.String(), nullable=True, comment='Carrier code or short name'))
    op.add_column('order_items', sa.Column('tracking_number', sa.String(), nullable=True, comment='Shipping tracking number'))
    op.add_column('order_items', sa.Column('tracking_url', sa.Text(), nullable=True, comment='Tracking URL provided by carrier'))
    op.add_column('order_items', sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True, comment='Datetime when the parcel was handed over to the carrier'))
    op.add_column('order_items', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True, comment='Datetime when the parcel was marked as delivered'))
    op.drop_constraint(op.f('order_items_product_make_id_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'makes', ['product_make_id'], ['make_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('order_items_product_make_id_fkey'), 'order_items', 'makes', ['product_make_id'], ['make_id'])
    op.drop_column('order_items', 'delivered_at')
    op.drop_column('order_items', 'shipped_at')
    op.drop_column('order_items', 'tracking_url')
    op.drop_column('order_items', 'tracking_number')
    op.drop_column('order_items', 'carrier_code')
    # ### end Alembic commands ###
